## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

import warnings
warnings.filterwarnings("ignore")

#  Import and read the charity_data.csv.
import pandas as pd
df_application = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
df_application.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
df_applications = df_application.drop(columns = ["EIN", "NAME"])
df_applications.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
df_applications.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
count_apps =df_applications.APPLICATION_TYPE.value_counts()
count_apps

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(count_apps[count_apps < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    df_applications['APPLICATION_TYPE'] = df_applications['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
df_applications['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
count_class =df_applications.CLASSIFICATION.value_counts()
count_class

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
#view classification counts > 1
count_class_gtone = count_class.loc[count_class > 1]
count_class_gtone

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(count_class[count_class < 800])
# Replace in dataframe
for cls in classifications_to_replace:
    df_applications['CLASSIFICATION'] = df_applications['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
df_applications['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
df_app_num = pd.get_dummies(df_applications)
df_app_num.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
from os import X_OK
# Split our preprocessed data into our features and target arrays
X= df_app_num.drop(['IS_SUCCESSFUL'], axis = 'columns').values
y = df_app_num['IS_SUCCESSFUL'].values

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# define the model - deep neural net
nn_model = tf.keras.models.Sequential()

number_input_features = len(X_train[0])
number_nodes_1 = 100
number_nodes_2 = 30
number_nodes_3 = 30
number_nodes_output = 1


# add first hidden layer
nn_model.add(
    tf.keras.layers.Dense(units=number_nodes_1, input_dim=number_input_features, activation=tf.keras.layers.LeakyReLU(alpha=0.01))
)

# add second hidden layer
nn_model.add(tf.keras.layers.Dense(units = number_nodes_2, input_dim = number_input_features, activation = "tanh"))

# add third hidden layer
nn_model.add(tf.keras.layers.Dense(units = number_nodes_3, input_dim = number_input_features, activation = "sigmoid"))


# add output layer

nn_model.add((tf.keras.layers.Dense(units = number_nodes_output, input_dim = number_input_features, activation = "sigmoid")))

# Check the structure of the model
nn_model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 100)               10900

 dense_1 (Dense)             (None, 30)                3030

 dense_2 (Dense)             (None, 30)                930

 dense_3 (Dense)             (None, 1)                 31

=================================================================
Total params: 14891 (58.17 KB)
Trainable params: 14891 (58.17 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn_model.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [14]:
# Train the model
fit_model = nn_model.fit(X_train_scaled, y_train, epochs=75)

Epoch 1/75
804/804 [==============================] - 3s 2ms/step - loss: 0.5770 - accuracy: 0.7141
Epoch 2/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5537 - accuracy: 0.7285
Epoch 3/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5494 - accuracy: 0.7317
Epoch 4/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5483 - accuracy: 0.7315
Epoch 5/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5468 - accuracy: 0.7315
Epoch 6/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7311
Epoch 7/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7314
Epoch 8/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7352
Epoch 9/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7341
Epoch 10/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7339
Epoch 11/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5413 - accuracy: 0.7336
Epoch 12/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7352
Epoch 13/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7357
Epoch 14/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5394 - accuracy: 0.7365
Epoch 15/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7368
Epoch 16/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5384 - accuracy: 0.7374
Epoch 17/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7372
Epoch 18/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5379 - accuracy: 0.7378
Epoch 19/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7364
Epoch 20/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7376
Epoch 21/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7376
Epoch 22/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7376
Epoch 23/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7384
Epoch 24/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7386
Epoch 25/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5351 - accuracy: 0.7383
Epoch 26/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7377
Epoch 27/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5348 - accuracy: 0.7383
Epoch 28/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5346 - accuracy: 0.7396
Epoch 29/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7391
Epoch 30/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5342 - accuracy: 0.7376
Epoch 31/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7401
Epoch 32/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5334 - accuracy: 0.7391
Epoch 33/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7399
Epoch 34/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5330 - accuracy: 0.7392
Epoch 35/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5327 - accuracy: 0.7401
Epoch 36/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7399
Epoch 37/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5322 - accuracy: 0.7399
Epoch 38/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5329 - accuracy: 0.7403
Epoch 39/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5325 - accuracy: 0.7404
Epoch 40/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7392
Epoch 41/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5325 - accuracy: 0.7395
Epoch 42/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7406
Epoch 43/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5315 - accuracy: 0.7400
Epoch 44/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7405
Epoch 45/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5319 - accuracy: 0.7398
Epoch 46/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7400
Epoch 47/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7412
Epoch 48/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5314 - accuracy: 0.7407
Epoch 49/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7416
Epoch 50/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5313 - accuracy: 0.7397
Epoch 51/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5308 - accuracy: 0.7413
Epoch 52/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5310 - accuracy: 0.7407
Epoch 53/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5303 - accuracy: 0.7415
Epoch 54/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7417
Epoch 55/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7408
Epoch 56/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7407
Epoch 57/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7413
Epoch 58/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5305 - accuracy: 0.7409
Epoch 59/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7416
Epoch 60/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5302 - accuracy: 0.7406
Epoch 61/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7421
Epoch 62/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7416
Epoch 63/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5301 - accuracy: 0.7412
Epoch 64/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7413
Epoch 65/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5303 - accuracy: 0.7411
Epoch 66/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7408
Epoch 67/75
804/804 [==============================] - 3s 3ms/step - loss: 0.5297 - accuracy: 0.7415
Epoch 68/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7409
Epoch 69/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7414
Epoch 70/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7419
Epoch 71/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7395
Epoch 72/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5299 - accuracy: 0.7411
Epoch 73/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5298 - accuracy: 0.7404
Epoch 74/75
804/804 [==============================] - 2s 3ms/step - loss: 0.5299 - accuracy: 0.7413
Epoch 75/75
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7408

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn_model.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5555 - accuracy: 0.7271 - 752ms/epoch - 3ms/step
Loss: 0.5555157661437988, Accuracy: 0.7271137237548828

In [ ]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE